In [1]:
# Import the necessary libraries
import sqlite3
import pandas as pd

In [2]:
conn = sqlite3.connect('./Data/im.db')

In [3]:
query = """
    SELECT *
    FROM sqlite_master;
"""
pd.read_sql(query, conn)

,type,name,tbl_name,rootpage,sql
0,table,movie_basics,movie_basics,2,"CREATE TABLE ""movie_basics"" (\n""movie_id"" TEXT..."
1,table,directors,directors,3,"CREATE TABLE ""directors"" (\n""movie_id"" TEXT,\n..."
2,table,known_for,known_for,4,"CREATE TABLE ""known_for"" (\n""person_id"" TEXT,\..."
3,table,movie_akas,movie_akas,5,"CREATE TABLE ""movie_akas"" (\n""movie_id"" TEXT,\..."
4,table,movie_ratings,movie_ratings,6,"CREATE TABLE ""movie_ratings"" (\n""movie_id"" TEX..."
5,table,persons,persons,7,"CREATE TABLE ""persons"" (\n""person_id"" TEXT,\n ..."
6,table,principals,principals,8,"CREATE TABLE ""principals"" (\n""movie_id"" TEXT,\..."
7,table,writers,writers,9,"CREATE TABLE ""writers"" (\n""movie_id"" TEXT,\n ..."

In [4]:
query = """
    SELECT *
    FROM movie_basics
    LIMIT 5;
"""
pd.read_sql(query, conn)

,movie_id,primary_title,original_title,start_year,runtime_minutes,genres
0,tt0063540,Sunghursh,Sunghursh,2013,175.0,"Action,Crime,Drama"
1,tt0066787,One Day Before the Rainy Season,Ashad Ka Ek Din,2019,114.0,"Biography,Drama"
2,tt0069049,The Other Side of the Wind,The Other Side of the Wind,2018,122.0,Drama
3,tt0069204,Sabse Bada Sukh,Sabse Bada Sukh,2018,NaN,"Comedy,Drama"
4,tt0100275,The Wandering Soap Opera,La Telenovela Errante,2017,80.0,"Comedy,Drama,Fantasy"

In [5]:
query = """
    SELECT *
    FROM movie_ratings
    LIMIT 5;
"""
pd.read_sql(query, conn)

     movie_id  averagerating  numvotes
0  tt10356526            8.3        31
1  tt10384606            8.9       559
2   tt1042974            6.4        20
3   tt1043726            4.2     50352
4   tt1060240            6.5        21

In [6]:
query = """
    SELECT ma.*
    FROM movie_akas AS ma
    LIMIT 5
"""
pd.read_sql(query, conn)

,movie_id,ordering,title,region,language,types,attributes,is_original_title
0,tt0369610,10,Джурасик свят,BG,bg,None,None,0.0
1,tt0369610,11,Jurashikku warudo,JP,None,imdbDisplay,None,0.0
2,tt0369610,12,Jurassic World: O Mundo dos Dinossauros,BR,None,imdbDisplay,None,0.0
3,tt0369610,13,O Mundo dos Dinossauros,BR,None,None,short title,0.0
4,tt0369610,14,Jurassic World,FR,None,imdbDisplay,None,0.0

In [7]:
query = """
    SELECT w.*
    FROM writers as w
    LIMIT 5;
"""
pd.read_sql(query, conn)

    movie_id  person_id
0  tt0285252  nm0899854
1  tt0438973  nm0175726
2  tt0438973  nm1802864
3  tt0462036  nm1940585
4  tt0835418  nm0310087

In [8]:
query = """
    SELECT d.*
    FROM directors as d
    LIMIT 5;
"""
pd.read_sql(query, conn)

    movie_id  person_id
0  tt0285252  nm0899854
1  tt0462036  nm1940585
2  tt0835418  nm0151540
3  tt0835418  nm0151540
4  tt0878654  nm0089502

In [9]:
query = """
    SELECT p.*
    FROM principals as p
    LIMIT 5;
"""
pd.read_sql(query, conn)

    movie_id  ordering  person_id  category       job        characters
0  tt0111414         1  nm0246005     actor      None       ["The Man"]
1  tt0111414         2  nm0398271  director      None              None
2  tt0111414         3  nm3739909  producer  producer              None
3  tt0323808        10  nm0059247    editor      None              None
4  tt0323808         1  nm3579312   actress      None  ["Beth Boothby"]

In [10]:
query = """
    SELECT ps.person_id, ps.primary_name, ps.primary_profession
    FROM persons as ps
    LIMIT 5;
"""
pd.read_sql(query, conn)

,person_id,primary_name,primary_profession
0,nm0061671,Mary Ellen Bauder,"miscellaneous,production_manager,producer"
1,nm0061865,Joseph Bauer,"composer,music_department,sound_department"
2,nm0062070,Bruce Baum,"miscellaneous,actor,writer"
3,nm0062195,Axel Baumann,"camera_department,cinematographer,art_department"
4,nm0062798,Pete Baxter,"production_designer,art_department,set_decorator"

In [11]:
query = """    
    SELECT  mb.movie_id, mb.original_title, mb.start_year, mb.runtime_minutes, mb.genres, 
            mr.averagerating, mr.numvotes, 
            ma.region, ma.language, ma.is_original_title,
            w.person_id AS writers_id,
            d.person_id AS director_id,
            w.person_id AS writer_id,
            d.person_id AS director_id,
            p.person_id AS principals_id, p.category, p.job, p.ordering
    FROM movie_basics AS mb
        FULL JOIN movie_ratings AS mr
            ON mb.movie_id = mr.movie_id
        FULL JOIN movie_akas AS ma
            ON mb.movie_id = ma.movie_id
        FULL JOIN writers as w
            ON mb.movie_id = w.movie_id
        FULL JOIN directors as d
            ON mb.movie_id = d.movie_id
        FULL JOIN principals AS p
            ON mb.movie_id = p.movie_id
    LIMIT 5;
"""
df = pd.read_sql(query, conn)
df

,movie_id,original_title,start_year,runtime_minutes,genres,averagerating,numvotes,region,language,is_original_title,writers_id,director_id,writer_id,director_id,principals_id,category,job,ordering
0,tt0063540,Sunghursh,2013,175.0,"Action,Crime,Drama",7.0,77,IN,hi,0.0,nm0023551,nm0712540,nm0023551,nm0712540,nm0006210,composer,None,10
1,tt0063540,Sunghursh,2013,175.0,"Action,Crime,Drama",7.0,77,IN,hi,0.0,nm0023551,nm0712540,nm0023551,nm0712540,nm0474801,actor,None,1
2,tt0063540,Sunghursh,2013,175.0,"Action,Crime,Drama",7.0,77,IN,hi,0.0,nm0023551,nm0712540,nm0023551,nm0712540,nm0904537,actress,None,2
3,tt0063540,Sunghursh,2013,175.0,"Action,Crime,Drama",7.0,77,IN,hi,0.0,nm0023551,nm0712540,nm0023551,nm0712540,nm0756379,actor,None,3
4,tt0063540,Sunghursh,2013,175.0,"Action,Crime,Drama",7.0,77,IN,hi,0.0,nm0023551,nm0712540,nm0023551,nm0712540,nm0474876,actor,None,4